services:
  - type: web
    name: socialguard-backend
    env: docker
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: SCRAPINGBEE_API_KEY
        sync: false
      - key: PROXY_URL
        sync: false


